# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shivom/projects/sniffles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shivom/projects/sniffles

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shivom/projects/sniffles/CMakeFiles /Users/shivom/projects/sniffles//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shivom/projects/sniffles/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sniffles

# Build rule for target.
sniffles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles
.PHONY : sniffles

# fast build rule for target.
sniffles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/build
.PHONY : sniffles/fast

#=============================================================================
# Target rules for targets named sniffles_qmltyperegistration

# Build rule for target.
sniffles_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_qmltyperegistration
.PHONY : sniffles_qmltyperegistration

# fast build rule for target.
sniffles_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_qmltyperegistration.dir/build.make CMakeFiles/sniffles_qmltyperegistration.dir/build
.PHONY : sniffles_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmltyperegistrations.dir/build.make CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named sniffles_qmllint

# Build rule for target.
sniffles_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_qmllint
.PHONY : sniffles_qmllint

# fast build rule for target.
sniffles_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_qmllint.dir/build.make CMakeFiles/sniffles_qmllint.dir/build
.PHONY : sniffles_qmllint/fast

#=============================================================================
# Target rules for targets named sniffles_qmllint_json

# Build rule for target.
sniffles_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_qmllint_json
.PHONY : sniffles_qmllint_json

# fast build rule for target.
sniffles_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_qmllint_json.dir/build.make CMakeFiles/sniffles_qmllint_json.dir/build
.PHONY : sniffles_qmllint_json/fast

#=============================================================================
# Target rules for targets named sniffles_qmllint_module

# Build rule for target.
sniffles_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_qmllint_module
.PHONY : sniffles_qmllint_module

# fast build rule for target.
sniffles_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_qmllint_module.dir/build.make CMakeFiles/sniffles_qmllint_module.dir/build
.PHONY : sniffles_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint.dir/build.make CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint_json.dir/build.make CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint_module.dir/build.make CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named sniffles_copy_qml

# Build rule for target.
sniffles_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_copy_qml
.PHONY : sniffles_copy_qml

# fast build rule for target.
sniffles_copy_qml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_copy_qml.dir/build.make CMakeFiles/sniffles_copy_qml.dir/build
.PHONY : sniffles_copy_qml/fast

#=============================================================================
# Target rules for targets named sniffles_copy_res

# Build rule for target.
sniffles_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_copy_res
.PHONY : sniffles_copy_res

# fast build rule for target.
sniffles_copy_res/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_copy_res.dir/build.make CMakeFiles/sniffles_copy_res.dir/build
.PHONY : sniffles_copy_res/fast

#=============================================================================
# Target rules for targets named capture

# Build rule for target.
capture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capture
.PHONY : capture

# fast build rule for target.
capture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/build
.PHONY : capture/fast

#=============================================================================
# Target rules for targets named LiveCapture

# Build rule for target.
LiveCapture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LiveCapture
.PHONY : LiveCapture

# fast build rule for target.
LiveCapture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/build
.PHONY : LiveCapture/fast

#=============================================================================
# Target rules for targets named module_sniffles_aotstats_target

# Build rule for target.
module_sniffles_aotstats_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 module_sniffles_aotstats_target
.PHONY : module_sniffles_aotstats_target

# fast build rule for target.
module_sniffles_aotstats_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/module_sniffles_aotstats_target.dir/build.make CMakeFiles/module_sniffles_aotstats_target.dir/build
.PHONY : module_sniffles_aotstats_target/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_aotstats.dir/build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named sniffles_qmlimportscan

# Build rule for target.
sniffles_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_qmlimportscan
.PHONY : sniffles_qmlimportscan

# fast build rule for target.
sniffles_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_qmlimportscan.dir/build.make CMakeFiles/sniffles_qmlimportscan.dir/build
.PHONY : sniffles_qmlimportscan/fast

#=============================================================================
# Target rules for targets named sniffles_autogen_timestamp_deps

# Build rule for target.
sniffles_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_autogen_timestamp_deps
.PHONY : sniffles_autogen_timestamp_deps

# fast build rule for target.
sniffles_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_autogen_timestamp_deps.dir/build.make CMakeFiles/sniffles_autogen_timestamp_deps.dir/build
.PHONY : sniffles_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named sniffles_autogen

# Build rule for target.
sniffles_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_autogen
.PHONY : sniffles_autogen

# fast build rule for target.
sniffles_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_autogen.dir/build.make CMakeFiles/sniffles_autogen.dir/build
.PHONY : sniffles_autogen/fast

#=============================================================================
# Target rules for targets named capture_autogen_timestamp_deps

# Build rule for target.
capture_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capture_autogen_timestamp_deps
.PHONY : capture_autogen_timestamp_deps

# fast build rule for target.
capture_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture_autogen_timestamp_deps.dir/build.make CMakeFiles/capture_autogen_timestamp_deps.dir/build
.PHONY : capture_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named capture_autogen

# Build rule for target.
capture_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capture_autogen
.PHONY : capture_autogen

# fast build rule for target.
capture_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture_autogen.dir/build.make CMakeFiles/capture_autogen.dir/build
.PHONY : capture_autogen/fast

#=============================================================================
# Target rules for targets named LiveCapture_autogen_timestamp_deps

# Build rule for target.
LiveCapture_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LiveCapture_autogen_timestamp_deps
.PHONY : LiveCapture_autogen_timestamp_deps

# fast build rule for target.
LiveCapture_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture_autogen_timestamp_deps.dir/build.make CMakeFiles/LiveCapture_autogen_timestamp_deps.dir/build
.PHONY : LiveCapture_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named LiveCapture_autogen

# Build rule for target.
LiveCapture_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LiveCapture_autogen
.PHONY : LiveCapture_autogen

# fast build rule for target.
LiveCapture_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture_autogen.dir/build.make CMakeFiles/LiveCapture_autogen.dir/build
.PHONY : LiveCapture_autogen/fast

.qt/rcc/qrc_qmake_sniffles.o: .qt/rcc/qrc_qmake_sniffles.cpp.o
.PHONY : .qt/rcc/qrc_qmake_sniffles.o

# target to build an object file
.qt/rcc/qrc_qmake_sniffles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_qmake_sniffles.cpp.o
.PHONY : .qt/rcc/qrc_qmake_sniffles.cpp.o

.qt/rcc/qrc_qmake_sniffles.i: .qt/rcc/qrc_qmake_sniffles.cpp.i
.PHONY : .qt/rcc/qrc_qmake_sniffles.i

# target to preprocess a source file
.qt/rcc/qrc_qmake_sniffles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_qmake_sniffles.cpp.i
.PHONY : .qt/rcc/qrc_qmake_sniffles.cpp.i

.qt/rcc/qrc_qmake_sniffles.s: .qt/rcc/qrc_qmake_sniffles.cpp.s
.PHONY : .qt/rcc/qrc_qmake_sniffles.s

# target to generate assembly for a file
.qt/rcc/qrc_qmake_sniffles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_qmake_sniffles.cpp.s
.PHONY : .qt/rcc/qrc_qmake_sniffles.cpp.s

.qt/rcc/qrc_sniffles_raw_qml_0.o: .qt/rcc/qrc_sniffles_raw_qml_0.cpp.o
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.o

# target to build an object file
.qt/rcc/qrc_sniffles_raw_qml_0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_sniffles_raw_qml_0.cpp.o
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.cpp.o

.qt/rcc/qrc_sniffles_raw_qml_0.i: .qt/rcc/qrc_sniffles_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.i

# target to preprocess a source file
.qt/rcc/qrc_sniffles_raw_qml_0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_sniffles_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.cpp.i

.qt/rcc/qrc_sniffles_raw_qml_0.s: .qt/rcc/qrc_sniffles_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.s

# target to generate assembly for a file
.qt/rcc/qrc_sniffles_raw_qml_0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.qt/rcc/qrc_sniffles_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_sniffles_raw_qml_0.cpp.s

.rcc/qmlcache/sniffles_main_qml.o: .rcc/qmlcache/sniffles_main_qml.cpp.o
.PHONY : .rcc/qmlcache/sniffles_main_qml.o

# target to build an object file
.rcc/qmlcache/sniffles_main_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_main_qml.cpp.o
.PHONY : .rcc/qmlcache/sniffles_main_qml.cpp.o

.rcc/qmlcache/sniffles_main_qml.i: .rcc/qmlcache/sniffles_main_qml.cpp.i
.PHONY : .rcc/qmlcache/sniffles_main_qml.i

# target to preprocess a source file
.rcc/qmlcache/sniffles_main_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_main_qml.cpp.i
.PHONY : .rcc/qmlcache/sniffles_main_qml.cpp.i

.rcc/qmlcache/sniffles_main_qml.s: .rcc/qmlcache/sniffles_main_qml.cpp.s
.PHONY : .rcc/qmlcache/sniffles_main_qml.s

# target to generate assembly for a file
.rcc/qmlcache/sniffles_main_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_main_qml.cpp.s
.PHONY : .rcc/qmlcache/sniffles_main_qml.cpp.s

.rcc/qmlcache/sniffles_qmlcache_loader.o: .rcc/qmlcache/sniffles_qmlcache_loader.cpp.o
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.o

# target to build an object file
.rcc/qmlcache/sniffles_qmlcache_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_qmlcache_loader.cpp.o
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.cpp.o

.rcc/qmlcache/sniffles_qmlcache_loader.i: .rcc/qmlcache/sniffles_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.i

# target to preprocess a source file
.rcc/qmlcache/sniffles_qmlcache_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.cpp.i

.rcc/qmlcache/sniffles_qmlcache_loader.s: .rcc/qmlcache/sniffles_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.s

# target to generate assembly for a file
.rcc/qmlcache/sniffles_qmlcache_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/.rcc/qmlcache/sniffles_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/sniffles_qmlcache_loader.cpp.s

LiveCapture_autogen/mocs_compilation.o: LiveCapture_autogen/mocs_compilation.cpp.o
.PHONY : LiveCapture_autogen/mocs_compilation.o

# target to build an object file
LiveCapture_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/LiveCapture_autogen/mocs_compilation.cpp.o
.PHONY : LiveCapture_autogen/mocs_compilation.cpp.o

LiveCapture_autogen/mocs_compilation.i: LiveCapture_autogen/mocs_compilation.cpp.i
.PHONY : LiveCapture_autogen/mocs_compilation.i

# target to preprocess a source file
LiveCapture_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/LiveCapture_autogen/mocs_compilation.cpp.i
.PHONY : LiveCapture_autogen/mocs_compilation.cpp.i

LiveCapture_autogen/mocs_compilation.s: LiveCapture_autogen/mocs_compilation.cpp.s
.PHONY : LiveCapture_autogen/mocs_compilation.s

# target to generate assembly for a file
LiveCapture_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/LiveCapture_autogen/mocs_compilation.cpp.s
.PHONY : LiveCapture_autogen/mocs_compilation.cpp.s

capture_autogen/mocs_compilation.o: capture_autogen/mocs_compilation.cpp.o
.PHONY : capture_autogen/mocs_compilation.o

# target to build an object file
capture_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture_autogen/mocs_compilation.cpp.o
.PHONY : capture_autogen/mocs_compilation.cpp.o

capture_autogen/mocs_compilation.i: capture_autogen/mocs_compilation.cpp.i
.PHONY : capture_autogen/mocs_compilation.i

# target to preprocess a source file
capture_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture_autogen/mocs_compilation.cpp.i
.PHONY : capture_autogen/mocs_compilation.cpp.i

capture_autogen/mocs_compilation.s: capture_autogen/mocs_compilation.cpp.s
.PHONY : capture_autogen/mocs_compilation.s

# target to generate assembly for a file
capture_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture_autogen/mocs_compilation.cpp.s
.PHONY : capture_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/main.cpp.s
.PHONY : main.cpp.s

sniffles_autogen/mocs_compilation.o: sniffles_autogen/mocs_compilation.cpp.o
.PHONY : sniffles_autogen/mocs_compilation.o

# target to build an object file
sniffles_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_autogen/mocs_compilation.cpp.o
.PHONY : sniffles_autogen/mocs_compilation.cpp.o

sniffles_autogen/mocs_compilation.i: sniffles_autogen/mocs_compilation.cpp.i
.PHONY : sniffles_autogen/mocs_compilation.i

# target to preprocess a source file
sniffles_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_autogen/mocs_compilation.cpp.i
.PHONY : sniffles_autogen/mocs_compilation.cpp.i

sniffles_autogen/mocs_compilation.s: sniffles_autogen/mocs_compilation.cpp.s
.PHONY : sniffles_autogen/mocs_compilation.s

# target to generate assembly for a file
sniffles_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_autogen/mocs_compilation.cpp.s
.PHONY : sniffles_autogen/mocs_compilation.cpp.s

sniffles_qmltyperegistrations.o: sniffles_qmltyperegistrations.cpp.o
.PHONY : sniffles_qmltyperegistrations.o

# target to build an object file
sniffles_qmltyperegistrations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_qmltyperegistrations.cpp.o
.PHONY : sniffles_qmltyperegistrations.cpp.o

sniffles_qmltyperegistrations.i: sniffles_qmltyperegistrations.cpp.i
.PHONY : sniffles_qmltyperegistrations.i

# target to preprocess a source file
sniffles_qmltyperegistrations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_qmltyperegistrations.cpp.i
.PHONY : sniffles_qmltyperegistrations.cpp.i

sniffles_qmltyperegistrations.s: sniffles_qmltyperegistrations.cpp.s
.PHONY : sniffles_qmltyperegistrations.s

# target to generate assembly for a file
sniffles_qmltyperegistrations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/sniffles_qmltyperegistrations.cpp.s
.PHONY : sniffles_qmltyperegistrations.cpp.s

src/LiveCapture.o: src/LiveCapture.cpp.o
.PHONY : src/LiveCapture.o

# target to build an object file
src/LiveCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/LiveCapture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/src/LiveCapture.cpp.o
.PHONY : src/LiveCapture.cpp.o

src/LiveCapture.i: src/LiveCapture.cpp.i
.PHONY : src/LiveCapture.i

# target to preprocess a source file
src/LiveCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/LiveCapture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/src/LiveCapture.cpp.i
.PHONY : src/LiveCapture.cpp.i

src/LiveCapture.s: src/LiveCapture.cpp.s
.PHONY : src/LiveCapture.s

# target to generate assembly for a file
src/LiveCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/LiveCapture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiveCapture.dir/build.make CMakeFiles/LiveCapture.dir/src/LiveCapture.cpp.s
.PHONY : src/LiveCapture.cpp.s

src/capture.o: src/capture.cpp.o
.PHONY : src/capture.o

# target to build an object file
src/capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.o
.PHONY : src/capture.cpp.o

src/capture.i: src/capture.cpp.i
.PHONY : src/capture.i

# target to preprocess a source file
src/capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.i
.PHONY : src/capture.cpp.i

src/capture.s: src/capture.cpp.s
.PHONY : src/capture.s

# target to generate assembly for a file
src/capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.s
.PHONY : src/capture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LiveCapture_autogen"
	@echo "... LiveCapture_autogen_timestamp_deps"
	@echo "... all_aotstats"
	@echo "... all_qmllint"
	@echo "... all_qmllint_json"
	@echo "... all_qmllint_module"
	@echo "... all_qmltyperegistrations"
	@echo "... capture_autogen"
	@echo "... capture_autogen_timestamp_deps"
	@echo "... module_sniffles_aotstats_target"
	@echo "... sniffles_autogen"
	@echo "... sniffles_autogen_timestamp_deps"
	@echo "... sniffles_copy_qml"
	@echo "... sniffles_copy_res"
	@echo "... sniffles_qmlimportscan"
	@echo "... sniffles_qmllint"
	@echo "... sniffles_qmllint_json"
	@echo "... sniffles_qmllint_module"
	@echo "... sniffles_qmltyperegistration"
	@echo "... LiveCapture"
	@echo "... capture"
	@echo "... sniffles"
	@echo "... .qt/rcc/qrc_qmake_sniffles.o"
	@echo "... .qt/rcc/qrc_qmake_sniffles.i"
	@echo "... .qt/rcc/qrc_qmake_sniffles.s"
	@echo "... .qt/rcc/qrc_sniffles_raw_qml_0.o"
	@echo "... .qt/rcc/qrc_sniffles_raw_qml_0.i"
	@echo "... .qt/rcc/qrc_sniffles_raw_qml_0.s"
	@echo "... .rcc/qmlcache/sniffles_main_qml.o"
	@echo "... .rcc/qmlcache/sniffles_main_qml.i"
	@echo "... .rcc/qmlcache/sniffles_main_qml.s"
	@echo "... .rcc/qmlcache/sniffles_qmlcache_loader.o"
	@echo "... .rcc/qmlcache/sniffles_qmlcache_loader.i"
	@echo "... .rcc/qmlcache/sniffles_qmlcache_loader.s"
	@echo "... LiveCapture_autogen/mocs_compilation.o"
	@echo "... LiveCapture_autogen/mocs_compilation.i"
	@echo "... LiveCapture_autogen/mocs_compilation.s"
	@echo "... capture_autogen/mocs_compilation.o"
	@echo "... capture_autogen/mocs_compilation.i"
	@echo "... capture_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sniffles_autogen/mocs_compilation.o"
	@echo "... sniffles_autogen/mocs_compilation.i"
	@echo "... sniffles_autogen/mocs_compilation.s"
	@echo "... sniffles_qmltyperegistrations.o"
	@echo "... sniffles_qmltyperegistrations.i"
	@echo "... sniffles_qmltyperegistrations.s"
	@echo "... src/LiveCapture.o"
	@echo "... src/LiveCapture.i"
	@echo "... src/LiveCapture.s"
	@echo "... src/capture.o"
	@echo "... src/capture.i"
	@echo "... src/capture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

