# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shivom/projects/sniffles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shivom/projects/sniffles

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shivom/projects/sniffles/CMakeFiles /Users/shivom/projects/sniffles//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shivom/projects/sniffles/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sniffles_core

# Build rule for target.
sniffles_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles_core
.PHONY : sniffles_core

# fast build rule for target.
sniffles_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/build
.PHONY : sniffles_core/fast

#=============================================================================
# Target rules for targets named sniffles

# Build rule for target.
sniffles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffles
.PHONY : sniffles

# fast build rule for target.
sniffles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/build
.PHONY : sniffles/fast

#=============================================================================
# Target rules for targets named test_decode

# Build rule for target.
test_decode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_decode
.PHONY : test_decode

# fast build rule for target.
test_decode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_decode.dir/build.make CMakeFiles/test_decode.dir/build
.PHONY : test_decode/fast

src/app/App.o: src/app/App.cpp.o
.PHONY : src/app/App.o

# target to build an object file
src/app/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/app/App.cpp.o
.PHONY : src/app/App.cpp.o

src/app/App.i: src/app/App.cpp.i
.PHONY : src/app/App.i

# target to preprocess a source file
src/app/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/app/App.cpp.i
.PHONY : src/app/App.cpp.i

src/app/App.s: src/app/App.cpp.s
.PHONY : src/app/App.s

# target to generate assembly for a file
src/app/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/app/App.cpp.s
.PHONY : src/app/App.cpp.s

src/capture/BpfFilter.o: src/capture/BpfFilter.cpp.o
.PHONY : src/capture/BpfFilter.o

# target to build an object file
src/capture/BpfFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/BpfFilter.cpp.o
.PHONY : src/capture/BpfFilter.cpp.o

src/capture/BpfFilter.i: src/capture/BpfFilter.cpp.i
.PHONY : src/capture/BpfFilter.i

# target to preprocess a source file
src/capture/BpfFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/BpfFilter.cpp.i
.PHONY : src/capture/BpfFilter.cpp.i

src/capture/BpfFilter.s: src/capture/BpfFilter.cpp.s
.PHONY : src/capture/BpfFilter.s

# target to generate assembly for a file
src/capture/BpfFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/BpfFilter.cpp.s
.PHONY : src/capture/BpfFilter.cpp.s

src/capture/CaptureService.o: src/capture/CaptureService.cpp.o
.PHONY : src/capture/CaptureService.o

# target to build an object file
src/capture/CaptureService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/CaptureService.cpp.o
.PHONY : src/capture/CaptureService.cpp.o

src/capture/CaptureService.i: src/capture/CaptureService.cpp.i
.PHONY : src/capture/CaptureService.i

# target to preprocess a source file
src/capture/CaptureService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/CaptureService.cpp.i
.PHONY : src/capture/CaptureService.cpp.i

src/capture/CaptureService.s: src/capture/CaptureService.cpp.s
.PHONY : src/capture/CaptureService.s

# target to generate assembly for a file
src/capture/CaptureService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/CaptureService.cpp.s
.PHONY : src/capture/CaptureService.cpp.s

src/capture/DeviceEnumerator.o: src/capture/DeviceEnumerator.cpp.o
.PHONY : src/capture/DeviceEnumerator.o

# target to build an object file
src/capture/DeviceEnumerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/DeviceEnumerator.cpp.o
.PHONY : src/capture/DeviceEnumerator.cpp.o

src/capture/DeviceEnumerator.i: src/capture/DeviceEnumerator.cpp.i
.PHONY : src/capture/DeviceEnumerator.i

# target to preprocess a source file
src/capture/DeviceEnumerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/DeviceEnumerator.cpp.i
.PHONY : src/capture/DeviceEnumerator.cpp.i

src/capture/DeviceEnumerator.s: src/capture/DeviceEnumerator.cpp.s
.PHONY : src/capture/DeviceEnumerator.s

# target to generate assembly for a file
src/capture/DeviceEnumerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/capture/DeviceEnumerator.cpp.s
.PHONY : src/capture/DeviceEnumerator.cpp.s

src/decode/Decoders.o: src/decode/Decoders.cpp.o
.PHONY : src/decode/Decoders.o

# target to build an object file
src/decode/Decoders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/Decoders.cpp.o
.PHONY : src/decode/Decoders.cpp.o

src/decode/Decoders.i: src/decode/Decoders.cpp.i
.PHONY : src/decode/Decoders.i

# target to preprocess a source file
src/decode/Decoders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/Decoders.cpp.i
.PHONY : src/decode/Decoders.cpp.i

src/decode/Decoders.s: src/decode/Decoders.cpp.s
.PHONY : src/decode/Decoders.s

# target to generate assembly for a file
src/decode/Decoders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/Decoders.cpp.s
.PHONY : src/decode/Decoders.cpp.s

src/decode/FlowTracker.o: src/decode/FlowTracker.cpp.o
.PHONY : src/decode/FlowTracker.o

# target to build an object file
src/decode/FlowTracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/FlowTracker.cpp.o
.PHONY : src/decode/FlowTracker.cpp.o

src/decode/FlowTracker.i: src/decode/FlowTracker.cpp.i
.PHONY : src/decode/FlowTracker.i

# target to preprocess a source file
src/decode/FlowTracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/FlowTracker.cpp.i
.PHONY : src/decode/FlowTracker.cpp.i

src/decode/FlowTracker.s: src/decode/FlowTracker.cpp.s
.PHONY : src/decode/FlowTracker.s

# target to generate assembly for a file
src/decode/FlowTracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/decode/FlowTracker.cpp.s
.PHONY : src/decode/FlowTracker.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles.dir/build.make CMakeFiles/sniffles.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/MainWindow.o: src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.o

# target to build an object file
src/ui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.cpp.o

src/ui/MainWindow.i: src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.i

# target to preprocess a source file
src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.cpp.i

src/ui/MainWindow.s: src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.s

# target to generate assembly for a file
src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.cpp.s

src/ui/models/PacketTableModel.o: src/ui/models/PacketTableModel.cpp.o
.PHONY : src/ui/models/PacketTableModel.o

# target to build an object file
src/ui/models/PacketTableModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/models/PacketTableModel.cpp.o
.PHONY : src/ui/models/PacketTableModel.cpp.o

src/ui/models/PacketTableModel.i: src/ui/models/PacketTableModel.cpp.i
.PHONY : src/ui/models/PacketTableModel.i

# target to preprocess a source file
src/ui/models/PacketTableModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/models/PacketTableModel.cpp.i
.PHONY : src/ui/models/PacketTableModel.cpp.i

src/ui/models/PacketTableModel.s: src/ui/models/PacketTableModel.cpp.s
.PHONY : src/ui/models/PacketTableModel.s

# target to generate assembly for a file
src/ui/models/PacketTableModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/ui/models/PacketTableModel.cpp.s
.PHONY : src/ui/models/PacketTableModel.cpp.s

src/util/Logging.o: src/util/Logging.cpp.o
.PHONY : src/util/Logging.o

# target to build an object file
src/util/Logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Logging.cpp.o
.PHONY : src/util/Logging.cpp.o

src/util/Logging.i: src/util/Logging.cpp.i
.PHONY : src/util/Logging.i

# target to preprocess a source file
src/util/Logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Logging.cpp.i
.PHONY : src/util/Logging.cpp.i

src/util/Logging.s: src/util/Logging.cpp.s
.PHONY : src/util/Logging.s

# target to generate assembly for a file
src/util/Logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Logging.cpp.s
.PHONY : src/util/Logging.cpp.s

src/util/Time.o: src/util/Time.cpp.o
.PHONY : src/util/Time.o

# target to build an object file
src/util/Time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Time.cpp.o
.PHONY : src/util/Time.cpp.o

src/util/Time.i: src/util/Time.cpp.i
.PHONY : src/util/Time.i

# target to preprocess a source file
src/util/Time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Time.cpp.i
.PHONY : src/util/Time.cpp.i

src/util/Time.s: src/util/Time.cpp.s
.PHONY : src/util/Time.s

# target to generate assembly for a file
src/util/Time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffles_core.dir/build.make CMakeFiles/sniffles_core.dir/src/util/Time.cpp.s
.PHONY : src/util/Time.cpp.s

tests/test_decode.o: tests/test_decode.cpp.o
.PHONY : tests/test_decode.o

# target to build an object file
tests/test_decode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_decode.dir/build.make CMakeFiles/test_decode.dir/tests/test_decode.cpp.o
.PHONY : tests/test_decode.cpp.o

tests/test_decode.i: tests/test_decode.cpp.i
.PHONY : tests/test_decode.i

# target to preprocess a source file
tests/test_decode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_decode.dir/build.make CMakeFiles/test_decode.dir/tests/test_decode.cpp.i
.PHONY : tests/test_decode.cpp.i

tests/test_decode.s: tests/test_decode.cpp.s
.PHONY : tests/test_decode.s

# target to generate assembly for a file
tests/test_decode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_decode.dir/build.make CMakeFiles/test_decode.dir/tests/test_decode.cpp.s
.PHONY : tests/test_decode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... sniffles"
	@echo "... sniffles_core"
	@echo "... test_decode"
	@echo "... src/app/App.o"
	@echo "... src/app/App.i"
	@echo "... src/app/App.s"
	@echo "... src/capture/BpfFilter.o"
	@echo "... src/capture/BpfFilter.i"
	@echo "... src/capture/BpfFilter.s"
	@echo "... src/capture/CaptureService.o"
	@echo "... src/capture/CaptureService.i"
	@echo "... src/capture/CaptureService.s"
	@echo "... src/capture/DeviceEnumerator.o"
	@echo "... src/capture/DeviceEnumerator.i"
	@echo "... src/capture/DeviceEnumerator.s"
	@echo "... src/decode/Decoders.o"
	@echo "... src/decode/Decoders.i"
	@echo "... src/decode/Decoders.s"
	@echo "... src/decode/FlowTracker.o"
	@echo "... src/decode/FlowTracker.i"
	@echo "... src/decode/FlowTracker.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/MainWindow.o"
	@echo "... src/ui/MainWindow.i"
	@echo "... src/ui/MainWindow.s"
	@echo "... src/ui/models/PacketTableModel.o"
	@echo "... src/ui/models/PacketTableModel.i"
	@echo "... src/ui/models/PacketTableModel.s"
	@echo "... src/util/Logging.o"
	@echo "... src/util/Logging.i"
	@echo "... src/util/Logging.s"
	@echo "... src/util/Time.o"
	@echo "... src/util/Time.i"
	@echo "... src/util/Time.s"
	@echo "... tests/test_decode.o"
	@echo "... tests/test_decode.i"
	@echo "... tests/test_decode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

