set(__QT_DEPLOY_TARGET_sniffles_FILE /Users/shivom/projects/sniffles/bin/sniffles)
set(__QT_DEPLOY_TARGET_sniffles_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_capture_FILE /Users/shivom/projects/sniffles/bin/capture)
set(__QT_DEPLOY_TARGET_capture_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_LiveCapture_FILE /Users/shivom/projects/sniffles/bin/LiveCapture)
set(__QT_DEPLOY_TARGET_LiveCapture_TYPE EXECUTABLE)
